# Generated by Django 3.0 on 2021-05-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Content', '0002_auto_20210511_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='caption_content',
            field=models.TextField(blank=True, null=True, verbose_name='What is on your mind?'),
        ),
    ]
